version: "3.1"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: questions
      POSTGRES_USER: question-user
      POSTGRES_PASSWORD: question-pass

  # needs to run the migrations externally
  # test:
  #   image: kennycallado/uv-questions-api:v0-amd64
  #   ports:
  #     - "8000:80"
  #   environment:
  #     ROCKET_DATABASES: '{question={url="postgres://question-user:question-pass@database/questions"}}'
  #   depends_on:
  #     - database

# networks:
#   docker-network:
