version: "3.1"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: questions
      POSTGRES_USER: question-user
      POSTGRES_PASSWORD: question-pass

  # database:
  #   image: mariadb:10.3
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - docker-network
  #   environment:
  #     MARIADB_ROOT_PASSWORD: toor
  #     MARIADB_USER: sensacion-user
  #     MARIADB_PASSWORD: sensacion-pass
  #     MARIADB_DATABASE: sensacion
  #   # volumes:
  #     # - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  #     # - ./database/db-1-init.sql:/docker-entrypoint-initdb.d/1.sql
  #     # - ./database/db-2-admin.sql:/docker-entrypoint-initdb.d/2.sql
  #     # - ./database/db-3-data.sql:/docker-entrypoint-initdb.d/3.sql
  #   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - docker-network
  #   environment:
  #     PMA_HOST: database
  #   depends_on:
  #     - database

# networks:
#   docker-network:
