# docker build -t kennycallado/uv-question-api:vX-slim .

FROM busybox:latest

COPY ./target/release/uv-question-api /bin/uv-question-api
# COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/sensacion /bin/sensacion
COPY ./Rocket.toml /root

WORKDIR /root

CMD [ "uv-question-api" ]

