GET http://localhost:8000/health

# QUESTION
#{{{

GET http://localhost:8000/api/v1/question

GET http://localhost:8000/api/v1/question/5

POST http://localhost:8000/api/v1/question
Content-Type: application/json

{
    "q_type" : "range",
    "question": "What is the answer to life, the universe and everything?"
}

PUT http://localhost:8000/api/v1/question/6
Content-Type: application/json

{
  "q_type": "range",
  "question": "What is the answer to life?"
}

GET http://localhost:8000/api/v1/question/6

DELETE http://localhost:8000/api/v1/question/6

GET http://localhost:8000/api/v1/question
#}}}

# FORM
#{{{

GET http://localhost:8000/api/v1/form

GET http://localhost:8000/api/v1/form/1

POST http://localhost:8000/api/v1/form
Content-Type: application/json

{
  "title": "titulo 10",
  "description": "Questionnaire 10"
}

GET http://localhost:8000/api/v1/form/10

GET http://localhost:8000/api/v1/form/1

PUT http://localhost:8000/api/v1/form/1
Content-Type: application/json

{
  "id": 11212,
  "title": "titulo bla bla",
  "description": "Questionnaire 1 of 9",
  "questions": [
    {
      "id": 4,
      "q_type": "patata",
      "question": "patatas everywhere"
    },
    {
      "id": 3,
      "q_type": "range",
      "question": "¿Bla bla bla bla?"
    },
    {
      "id": 2,
      "q_type": "range",
      "question": "¿Bla bla bla?"
    }
  ]
}

GET http://localhost:8000/api/v1/form/1

GET http://localhost:8000/api/v1/form

#}}}
