GET http://localhost:8000/health

# QUESTION

GET http://localhost:8000/api/v1/question

GET http://localhost:8000/api/v1/question/5

POST http://localhost:8000/api/v1/question
Content-Type: application/json

{
    "q_type" : "range",
    "question": "What is the answer to life, the universe and everything?"
}

PUT http://localhost:8000/api/v1/question/6
Content-Type: application/json

{
  "q_type": "range",
  "question": "What is the answer to life?"
}

GET http://localhost:8000/api/v1/question/6

DELETE http://localhost:8000/api/v1/question/6

###

# FORM

GET http://localhost:8000/api/v1/form

GET http://localhost:8000/api/v1/form/1

POST http://localhost:8000/api/v1/form
Content-Type: application/json

{
  "title": "titulo 10",
  "description": "Questionnaire 10"
}

PUT http://localhost:8000/api/v1/form/10
Content-Type: application/json

{
  "title": "titulo 10",
  "description": "Questionnaire 10 of 9?"
}

GET http://localhost:8000/api/v1/form/10

DELETE http://localhost:8000/api/v1/form/10

# FORM-QUESTION

GET http://localhost:8000/api/v1/form_question

GET http://localhost:8000/api/v1/form_question/1

POST http://localhost:8000/api/v1/form_question
Content-Type: application/json

{
  "form_id": 1,
  "question_id": 1
}

PUT http://localhost:8000/api/v1/form_question/37
Content-Type: application/json

{
  "form_id": 1,
  "question_id": 3
}

GET http://localhost:8000/api/v1/form_question/37

DELETE http://localhost:8000/api/v1/form_question/37

GET http://localhost:8000/api/v1/form_question/form/1

###
